"""
pk_mix default=uuid.uuid4.

Revision ID: 1072ae6df896
Revises: 0aaeab7715c0
Create Date: 2025-08-04 05:41:30.999893
"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "1072ae6df896"
down_revision: Union[str, Sequence[str], None] = "0aaeab7715c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
